# Generated by Django 5.2 on 2025-04-14 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('mana_cost', models.TextField(blank=True, null=True)),
                ('type_line', models.TextField(blank=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('power', models.TextField(blank=True, null=True)),
                ('toughness', models.TextField(blank=True, null=True)),
                ('loyalty', models.TextField(blank=True, null=True)),
                ('colors', models.TextField(blank=True, null=True)),
                ('image_uris', models.TextField(blank=True, null=True)),
                ('quantity', models.IntegerField()),
                ('rarity', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('set_name', models.CharField(max_length=100)),
                ('set_code', models.CharField(blank=True, max_length=10, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
