# Generated by Django 5.2 on 2025-04-20 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='nick',
            new_name='nickname',
        ),
    ]
