# Generated by Django 5.2 on 2025-05-07 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_cardforsale_cartitem_purchase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar',
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar_file',
            field=models.ImageField(blank=True, help_text='Imagen subida por el usuario', null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar_url',
            field=models.URLField(blank=True, help_text='URL de un avatar remoto', null=True),
        ),
    ]
