# Generated by Django 5.2 on 2025-05-08 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_profile_avatar_profile_avatar_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardlisting',
            name='is_active',
        ),
    ]
