# Generated by Django 5.2 on 2025-05-08 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_cardlisting_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardlisting',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
