# Generated by Django 5.2 on 2025-05-18 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_profile_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Usuario'), (2, 'Moderador'), (3, 'Administrador')], default=1),
        ),
    ]
