# Generated by Django 5.2 on 2025-05-18 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_profile_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='role',
        ),
    ]
